kind: pipeline
name: default

steps:
  - name: tests
    image: capnrefsmmat/statcomp:0.1
    pull: never
    commands:
      - echo $DRONE_SOURCE_BRANCH
      - cd "$(.ci/get-dirname.py)"
      - echo 'Test results:\n'
      - comment.file
      - pytest -v >> comment.file
      - Rscript ../.ci/run-tests.R >> comment.file
      - echo '\n' >> comment.file

  - name: gh-comment
    image: jmccann/drone-github-comment:1
    message_file: comment.file

trigger:
  event:
    - pull_request
