kind: pipeline
name: default

steps:
  - name: R-tests
    image: capnrefsmmat/statcomp:0.1
    pull: never
    commands:
      - echo "Running all R tests in branch ${DRONE_SOURCE_BRANCH}."
      - echo "Looking in directory $(.ci/get-dirname.py)"
      - cd "$(.ci/get-dirname.py)"
      - Rscript ../.ci/run-tests.R

  - name: Python-tests
    image: capnrefsmmat/statcomp:0.1
    pull: never
    commands:
      - echo "Running all Python tests in branch ${DRONE_SOURCE_BRANCH}:"
      - echo "Looking in directory $(.ci/get-dirname.py)"
      - cd "$(.ci/get-dirname.py)"
      - pytest -v

trigger:
  event:
    - pull_request
